### PR TITLE
added solutions to SPOJ problems

### PR DESCRIPTION
**Pull request by Autoratch**

### CODE REVIEW

**Review by hhhrrrttt222111 — CHANGES_REQUESTED** [review]
Please create separate folder for each problem.
Also add a readme.md file inside each problem folder containing the link to the Problem. ;)

**Comment by hhhrrrttt222111** [comment]
@Autoratch 
Pls fix this immediately ;)

**Comment by Autoratch** [comment]
Done! :)

**Review by hhhrrrttt222111 — CHANGES_REQUESTED** [review]
Please create separate folder for each problem.
Also add a readme.md file inside each problem folder containing the link to the Problem. ;)

Eg: MORE CODING PLATFORMS/SPOJ/Acquire/acquire.cpp 
      MORE CODING PLATFORMS/SPOJ/Acquire/readme.md

for each files

**Review by K-u-n-a-l-c — APPROVED** [review]

**Pull request closed without merging**
