### PR TITLE
Create ForLoop.cpp

### PR DESCRIPTION
**Pull request by sej28**
https://www.hackerrank.com/challenges/c-tutorial-for-loop/problem

Adding C++ solution to ForLoop.cpp problem from HackerRank

### CODE REVIEW

**Review by hhhrrrttt222111 — CHANGES_REQUESTED** [review]
Create a new folder for each problem
Also insert readme.md with the problem link

**Comment by sej28** [comment]
okay, but then I will add readme file separately? ...after creating the folder and adding code in it

**Comment by hhhrrrttt222111** [comment]
> okay, but then I will add readme file separately? ...after creating the folder and adding code in it

Yep.
Once you have done and pushed, I'll merge ;)

**Comment by sej28** [comment]
cool... i will create the new pr for that then

**Pull request closed without merging**
