### PR TITLE
Movie Weekend (MOVIEWKN)

### PR DESCRIPTION
**Pull request by Vedika-Agrawal**
I have added my solution of code chef problem : Movie weekend.
Please review it and if any conflict plz let me know, I will fix it.

### CODE REVIEW

**Comment by hhhrrrttt222111** [comment]
> I have added my solution of code chef problem : Movie weekend. Please review it and if any conflict plz let me know, I will fix it.

Pls follow proper naming and folder structure. ;)

**Comment by Vedika-Agrawal** [comment]
Okay sir, Sir if I'm right I need to contribute to the  Beginner folder??

**Comment by hhhrrrttt222111** [comment]
> Okay sir, Sir if I'm right I need to contribute to the Beginner folder??

https://github.com/hhhrrrttt222111/CodeChef/blob/main/CONTRIBUTING.md

Follow these rules.
Create a folder for the problem.
Insert the code with proper extension.
Add a readme.md file with the Problem link

**Comment by Vedika-Agrawal** [comment]
Okay sir I will make all these necessary changes in a while.

**Pull request merged**
