### PR TITLE
Adding dart support for beginner level

### PR DESCRIPTION
**Pull request by GrbavaCigla**

### CODE REVIEW

**Comment by hhhrrrttt222111** [comment]
PR is still a draft

**Comment by GrbavaCigla** [comment]
Since some problems are missing solutions in other languages, I will add those as well.

**Comment by GrbavaCigla** [comment]
Why did you merge it? I wanted to add more solutions...

**Comment by hhhrrrttt222111** [comment]
> Why did you merge it? I wanted to add more solutions...

You can put another PR.

**Pull request merged**
